log:
  loglevel: info
dns:
  servers:
  - https+local://8.8.8.8/dns-query
inbounds:
- port: 8080
  protocol: trojan
  settings:
    clients:
    - password: "yuyieurw438487gyr"
  streamSettings:
    network: ws
    wsSettings:
      path: qwe
  sniffing:
    enabled: false
    destOverride:
    - http
    - tls
    - quic
outbounds:
- protocol: freedom
  tag: direct
  settings:
    domainStrategy: UseIPv4
